import { Question } from '@/types';

export const questions: Question[] = [
  { id: 1, text: "Held hands romantically?" },
  { id: 2, text: "Been on a date?" },
  { id: 3, text: "Been in a relationship?" },
  { id: 4, text: "Danced without leaving room for Jesus?" },
  { id: 5, text: "Kissed a non-family member?" },
  { id: 6, text: "Kissed a non-family member on the lips?" },
  { id: 7, text: "French kissed?" },
  { id: 8, text: "French kissed in public?" },
  { id: 9, text: "Kissed on the neck?" },
  { id: 10, text: "Kissed horizontally?" },
  { id: 11, text: "Had a hickey?" },
  { id: 12, text: "Kissed or been kissed on the breast?" },
  { id: 13, text: "Kissed someone below the belt?" },
  { id: 14, text: "Kissed for more than two hours consecutively?" },
  { id: 15, text: "Played a game involving stripping?" },
  { id: 16, text: "Seen or been seen by another person in a sensual context?" },
  { id: 17, text: "Masturbated?" },
  { id: 18, text: "Masturbated to a picture or video?" },
  { id: 19, text: "Masturbated while someone else was in the room?" },
  { id: 20, text: "Been caught masturbating?" },
  { id: 21, text: "Masturbated with an inanimate object?" },
  { id: 22, text: "Seen or read pornographic material?" },
  { id: 23, text: "Massaged or been massaged sensually?" },
  { id: 24, text: "Gone through the motions of intercourse while fully dressed?" },
  { id: 25, text: "Undressed or been undressed by a non-family member?" },
  { id: 26, text: "Showered with a non-family member?" },
  { id: 27, text: "Fondled or had your butt cheeks fondled?" },
  { id: 28, text: "Fondled or had your breasts fondled?" },
  { id: 29, text: "Fondled or had your genitals fondled?" },
  { id: 30, text: "Had or given 'blue balls'?" },
  { id: 31, text: "Had an orgasm due to someone else's manipulation?" },
  { id: 32, text: "Sent a sexually explicit text or instant message?" },
  { id: 33, text: "Sent or received sexually explicit photographs?" },
  { id: 34, text: "Engaged in sexually explicit activity over video chat?" },
  { id: 35, text: "Cheated on a significant other during a relationship?" },
  { id: 36, text: "Purchased contraceptives?" },
  { id: 37, text: "Gave oral sex?" },
  { id: 38, text: "Received oral sex?" },
  { id: 39, text: "Ingested someone else's genital secretion?" },
  { id: 40, text: "Used a sex toy with a partner?" },
  { id: 41, text: "Spent the night with someone you were attracted to?" },
  { id: 42, text: "Been walked in on while engaging in a sexual act?" },
  { id: 43, text: "Kicked a roommate out to commit a sexual act?" },
  { id: 44, text: "Ingested alcohol in a non-religious context?" },
  { id: 45, text: "Played a drinking game?" },
  { id: 46, text: "Been drunk?" },
  { id: 47, text: "Faked sobriety to parents or teachers?" },
  { id: 48, text: "Had severe memory loss due to alcohol?" },
  { id: 49, text: "Used tobacco?" },
  { id: 50, text: "Used marijuana?" },
  { id: 51, text: "Used a drug stronger than marijuana?" },
  { id: 52, text: "Used methamphetamine, crack cocaine, PCP, horse tranquilizers or heroin?" },
  { id: 53, text: "Been sent to the office of a principal, dean or judicial affairs representative for a disciplinary infraction?" },
  { id: 54, text: "Been put on disciplinary probation or suspended?" },
  { id: 55, text: "Had the police called on you?" },
  { id: 56, text: "Run from the police?" },
  { id: 57, text: "Had the police question you?" },
  { id: 58, text: "Had the police handcuff you?" },
  { id: 59, text: "Been arrested?" },
  { id: 60, text: "Been convicted of a crime?" },
  { id: 61, text: "Been convicted of a felony?" },
  { id: 62, text: "Committed an act of vandalism?" },
  { id: 63, text: "Had sexual intercourse?" },
  { id: 64, text: "Had sexual intercourse three or more times in one night?" },
  { id: 65, text: "Had sexual intercourse in three or more positions?" },
  { id: 66, text: "Had sexual intercourse in four or more positions?" },
  { id: 67, text: "Had sexual intercourse with a stranger or person you met within 24 hours?" },
  { id: 68, text: "Had sexual intercourse in a motor vehicle?" },
  { id: 69, text: "Had sexual intercourse outdoors?" },
  { id: 70, text: "Had sexual intercourse in public?" },
  { id: 71, text: "Had sexual intercourse in a swimming pool or hot tub?" },
  { id: 72, text: "Had sexual intercourse in a bed not belonging to you or your partner?" },
  { id: 73, text: "Had sexual intercourse while you or your partner's parents were in the same home?" },
  { id: 74, text: "Had sexual intercourse with non-participating third party in the same room?" },
  { id: 75, text: "Joined the mile high club?" },
  { id: 76, text: "Participated in a 'booty call' with a partner whom you were not in a relationship with?" },
  { id: 77, text: "Traveled 100 or more miles for the primary purpose of sexual intercourse?" },
  { id: 78, text: "Had sexual intercourse with a person whose name you did not know?" },
  { id: 79, text: "Had sexual intercourse with a person you never saw again?" },
  { id: 80, text: "Had sexual intercourse with someone you knew less than one month?" },
  { id: 81, text: "Had sexual intercourse with a virgin?" },
  { id: 82, text: "Had sexual intercourse without a condom?" },
  { id: 83, text: "Had a pregnancy scare?" },
  { id: 84, text: "Impregnated someone or been impregnated?" },
  { id: 85, text: "Paid or been paid for a sexual act?" },
  { id: 86, text: "Committed an act of voyeurism?" },
  { id: 87, text: "Snuck out of the house at night?" },
  { id: 88, text: "Kissed someone you met that same night?" },
  { id: 89, text: "Stayed out all night without telling anyone where you were?" },
  { id: 90, text: "Had a sexually transmitted infection?" },
  { id: 91, text: "Had sexual intercourse with more than one person in a 24 hour period?" },
  { id: 92, text: "Been in a threesome?" },
  { id: 93, text: "Attended an orgy?" },
  { id: 94, text: "Had two or more distinct acts of sexual intercourse with two or more people within 24 hours?" },
  { id: 95, text: "Had sexual intercourse with five or more partners?" },
  { id: 96, text: "Been photographed or filmed during sexual intercourse?" },
  { id: 97, text: "Had period sex?" },
  { id: 98, text: "Had anal sex?" },
  { id: 99, text: "Had a STI test due to reasonable suspicion?" },
  { id: 100, text: "Been involved in BDSM?" }
];

/**
 * How the list is organised. Ranges are inclusive question ids.
 * Used by the questions guide so the grouping always matches the real list.
 */
export const QUESTION_GROUPS: { name: string; from: number; to: number; summary: string }[] = [
  { name: 'Dating and kissing', from: 1, to: 14, summary: 'Holding hands, first dates, relationships and the different kinds of kissing.' },
  { name: 'Solo and private experiences', from: 15, to: 24, summary: 'Strip games, masturbation, adult material and non-intercourse intimacy.' },
  { name: 'Physical intimacy with a partner', from: 25, to: 43, summary: 'Undressing, touching, sexting, oral sex, contraception and being walked in on.' },
  { name: 'Alcohol, tobacco and drugs', from: 44, to: 52, summary: 'From a first drink to hard drugs.' },
  { name: 'Trouble with school or the law', from: 53, to: 62, summary: 'Being disciplined at school, police contact, arrests and convictions.' },
  { name: 'Sex, partners and risk', from: 63, to: 100, summary: 'Intercourse, locations, partners, protection, testing and a few nights out.' },
];
